<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run()
    {

        
        $data = [
            // Admin Users
            [
                'first_name' => 'Admin',
                'last_name' => 'User',
                'email' => 'admin@lms.com',
                'password' => password_hash('admin123', PASSWORD_DEFAULT),
                'role' => 'admin',
                'phone' => '+1234567890',
                'address' => '123 Admin Street, Admin City, AC 12345',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'System',
                'last_name' => 'Administrator',
                'email' => 'system@lms.com',
                'password' => password_hash('system123', PASSWORD_DEFAULT),
                'role' => 'admin',
                'phone' => '+1234567891',
                'address' => '456 System Ave, System Town, ST 67890',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Instructor Users
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'email' => 'john.smith@lms.com',
                'password' => password_hash('instructor123', PASSWORD_DEFAULT),
                'role' => 'instructor',
                'phone' => '+1234567892',
                'address' => '789 Teaching Blvd, Education City, EC 11111',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'email' => 'sarah.johnson@lms.com',
                'password' => password_hash('instructor123', PASSWORD_DEFAULT),
                'role' => 'instructor',
                'phone' => '+1234567893',
                'address' => '321 Learning Lane, Knowledge Town, KT 22222',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'email' => 'michael.brown@lms.com',
                'password' => password_hash('instructor123', PASSWORD_DEFAULT),
                'role' => 'instructor',
                'phone' => '+1234567894',
                'address' => '654 Professor Place, Academic City, AC 33333',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Davis',
                'email' => 'emily.davis@lms.com',
                'password' => password_hash('instructor123', PASSWORD_DEFAULT),
                'role' => 'instructor',
                'phone' => '+1234567895',
                'address' => '987 Scholar Street, University Town, UT 44444',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Student Users
            [
                'first_name' => 'Alice',
                'last_name' => 'Wilson',
                'email' => 'alice.wilson@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567896',
                'address' => '111 Student Street, College City, CC 55555',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Bob',
                'last_name' => 'Miller',
                'email' => 'bob.miller@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567897',
                'address' => '222 Learner Lane, Study Town, ST 66666',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Carol',
                'last_name' => 'Taylor',
                'email' => 'carol.taylor@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567898',
                'address' => '333 Graduate Grove, Diploma City, DC 77777',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Anderson',
                'email' => 'david.anderson@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567899',
                'address' => '444 Academic Ave, School Town, ST 88888',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Eva',
                'last_name' => 'Thomas',
                'email' => 'eva.thomas@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567900',
                'address' => '555 Education End, Learning City, LC 99999',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Frank',
                'last_name' => 'Jackson',
                'email' => 'frank.jackson@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567901',
                'address' => '666 Knowledge Knoll, Wisdom Town, WT 10101',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Grace',
                'last_name' => 'White',
                'email' => 'grace.white@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567902',
                'address' => '777 Scholar Street, Degree City, DC 12121',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Henry',
                'last_name' => 'Harris',
                'email' => 'henry.harris@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567903',
                'address' => '888 Campus Court, University City, UC 13131',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Ivy',
                'last_name' => 'Clark',
                'email' => 'ivy.clark@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567904',
                'address' => '999 Study Street, College Town, CT 14141',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Jack',
                'last_name' => 'Lewis',
                'email' => 'jack.lewis@student.com',
                'password' => password_hash('student123', PASSWORD_DEFAULT),
                'role' => 'student',
                'phone' => '+1234567905',
                'address' => '1010 Learning Lane, Academy City, AC 15151',
                'profile_image' => null,
                'is_active' => true,
                'email_verified_at' => date('Y-m-d H:i:s'),
                'last_login_at' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        // Insert the data
        $this->db->table('users')->insertBatch($data);
    }
}
