<?php $this->extend('template'); ?>

<?php $this->section('content'); ?>

<!-- Calendar Header -->
<div class="bg-primary text-white py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8">
                <h1 class="h3 mb-2">Schedule Calendar</h1>
                <p class="mb-0 opacity-75">
                    <i class="bi bi-calendar-week me-2"></i>
                    Visual calendar view of your course schedule
                </p>
            </div>
            <div class="col-lg-4 text-end">
                <div class="d-flex gap-2 justify-content-end">
                    <a href="<?= base_url('instructor/schedule') ?>" class="btn btn-outline-light">
                        <i class="bi bi-list me-2"></i>List View
                    </a>
                    <a href="<?= base_url('instructor/schedule/create') ?>" class="btn btn-light">
                        <i class="bi bi-plus-lg me-2"></i>Create Schedule
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Calendar Content -->
<div class="container mt-4">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h6 class="m-0 font-weight-bold text-primary">Calendar View</h6>
                        <div class="d-flex gap-2">
                            <div class="btn-group" role="group">
                                <button type="button" class="btn btn-sm btn-outline-primary" id="prevMonth">
                                    <i class="bi bi-chevron-left"></i>
                                </button>
                                <button type="button" class="btn btn-sm btn-outline-primary" id="currentMonth">
                                    <span id="currentMonthText">December 2024</span>
                                </button>
                                <button type="button" class="btn btn-sm btn-outline-primary" id="nextMonth">
                                    <i class="bi bi-chevron-right"></i>
                                </button>
                            </div>
                            <div class="btn-group" role="group">
                                <button type="button" class="btn btn-sm btn-outline-secondary active" data-view="month">Month</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary" data-view="week">Week</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary" data-view="day">Day</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body p-0">
                    <!-- Calendar Grid -->
                    <div class="calendar-container">
                        <!-- Calendar Header -->
                        <div class="calendar-header d-flex border-bottom">
                            <div class="calendar-day-header flex-fill text-center fw-semibold py-2">Sun</div>
                            <div class="calendar-day-header flex-fill text-center fw-semibold py-2">Mon</div>
                            <div class="calendar-day-header flex-fill text-center fw-semibold py-2">Tue</div>
                            <div class="calendar-day-header flex-fill text-center fw-semibold py-2">Wed</div>
                            <div class="calendar-day-header flex-fill text-center fw-semibold py-2">Thu</div>
                            <div class="calendar-day-header flex-fill text-center fw-semibold py-2">Fri</div>
                            <div class="calendar-day-header flex-fill text-center fw-semibold py-2">Sat</div>
                        </div>
                        
                        <!-- Calendar Days -->
                        <div class="calendar-grid" id="calendarGrid">
                            <!-- Calendar days will be generated by JavaScript -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Upcoming Events -->
    <div class="row mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-light py-3">
                    <h6 class="m-0 font-weight-bold text-info">
                        <i class="bi bi-calendar-event me-2"></i>Upcoming Events
                    </h6>
                </div>
                <div class="card-body">
                    <div id="upcomingEvents">
                        <!-- Events will be loaded here -->
                        <div class="text-center text-muted py-4">
                            <i class="bi bi-calendar-x fs-1 mb-3"></i>
                            <p>No upcoming events scheduled</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-md-4">
            <div class="card">
                <div class="card-header bg-light py-3">
                    <h6 class="m-0 font-weight-bold text-warning">
                        <i class="bi bi-info-circle me-2"></i>Calendar Legend
                    </h6>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <div class="d-flex align-items-center mb-2">
                            <div class="calendar-legend-item bg-primary me-2"></div>
                            <small>Lecture</small>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <div class="calendar-legend-item bg-warning me-2"></div>
                            <small>Assignment</small>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <div class="calendar-legend-item bg-danger me-2"></div>
                            <small>Exam</small>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <div class="calendar-legend-item bg-info me-2"></div>
                            <small>Laboratory</small>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <div class="calendar-legend-item bg-success me-2"></div>
                            <small>Project</small>
                        </div>
                        <div class="d-flex align-items-center">
                            <div class="calendar-legend-item bg-secondary me-2"></div>
                            <small>Other</small>
                        </div>
                    </div>
                    
                    <hr>
                    
                    <h6 class="fw-semibold mb-3">Quick Actions</h6>
                    <div class="d-grid gap-2">
                        <a href="<?= base_url('instructor/schedule/create') ?>" class="btn btn-primary btn-sm">
                            <i class="bi bi-plus me-1"></i>Add Event
                        </a>
                        <a href="<?= base_url('instructor/schedule') ?>" class="btn btn-outline-secondary btn-sm">
                            <i class="bi bi-list me-1"></i>List View
                        </a>
                        <button class="btn btn-outline-info btn-sm" id="exportCalendar">
                            <i class="bi bi-download me-1"></i>Export Calendar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Event Modal -->
<div class="modal fade" id="eventModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Event Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="eventModalBody">
                <!-- Event details will be loaded here -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="editEventBtn">Edit Event</button>
            </div>
        </div>
    </div>
</div>

<?php $this->endSection(); ?>

<?php $this->section('scripts'); ?>
<style>
.calendar-container {
    font-size: 14px;
}

.calendar-header {
    background-color: #f8f9fa;
}

.calendar-day-header {
    min-width: 14.28%;
    background-color: #e9ecef;
}

.calendar-grid {
    display: flex;
    flex-wrap: wrap;
    min-height: 400px;
}

.calendar-day {
    width: 14.28%;
    min-height: 100px;
    border-right: 1px solid #dee2e6;
    border-bottom: 1px solid #dee2e6;
    position: relative;
}

.calendar-day:nth-child(7n) {
    border-right: none;
}

.calendar-day-number {
    padding: 8px;
    font-weight: 500;
}

.calendar-day.other-month .calendar-day-number {
    color: #adb5bd;
}

.calendar-day.today .calendar-day-number {
    background-color: #007bff;
    color: white;
    border-radius: 50%;
    width: 28px;
    height: 28px;
    display: flex;
    align-items: center;
    justify-content: center;
}

.calendar-event {
    font-size: 11px;
    padding: 2px 4px;
    margin: 1px;
    border-radius: 3px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    cursor: pointer;
}

.calendar-legend-item {
    width: 16px;
    height: 16px;
    border-radius: 3px;
}
</style>

<script>
let currentDate = new Date();
let currentView = 'month';

// Calendar functionality
function generateCalendar(year, month) {
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const prevLastDay = new Date(year, month, 0);
    
    const firstDayOfWeek = firstDay.getDay();
    const lastDateOfMonth = lastDay.getDate();
    const prevLastDateOfMonth = prevLastDay.getDate();
    
    let html = '';
    
    // Previous month days
    for (let i = firstDayOfWeek; i > 0; i--) {
        html += `<div class="calendar-day other-month">
            <div class="calendar-day-number">${prevLastDateOfMonth - i + 1}</div>
        </div>`;
    }
    
    // Current month days
    const today = new Date();
    for (let i = 1; i <= lastDateOfMonth; i++) {
        const isToday = year === today.getFullYear() && 
                       month === today.getMonth() && 
                       i === today.getDate();
        
        html += `<div class="calendar-day ${isToday ? 'today' : ''}" data-date="${year}-${String(month + 1).padStart(2, '0')}-${String(i).padStart(2, '0')}">
            <div class="calendar-day-number">${i}</div>
            <div class="calendar-events"></div>
        </div>`;
    }
    
    // Next month days
    const remainingDays = 42 - (firstDayOfWeek + lastDateOfMonth);
    for (let i = 1; i <= remainingDays; i++) {
        html += `<div class="calendar-day other-month">
            <div class="calendar-day-number">${i}</div>
        </div>`;
    }
    
    $('#calendarGrid').html(html);
    updateMonthDisplay();
}

function updateMonthDisplay() {
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                       'July', 'August', 'September', 'October', 'November', 'December'];
    $('#currentMonthText').text(`${monthNames[currentDate.getMonth()]} ${currentDate.getFullYear()}`);
}

// Navigation
$('#prevMonth').on('click', function() {
    currentDate.setMonth(currentDate.getMonth() - 1);
    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
});

$('#nextMonth').on('click', function() {
    currentDate.setMonth(currentDate.getMonth() + 1);
    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
});

$('#currentMonth').on('click', function() {
    currentDate = new Date();
    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
});

// View switching
$('[data-view]').on('click', function() {
    $('[data-view]').removeClass('active');
    $(this).addClass('active');
    currentView = $(this).data('view');
    // Here you would implement different view logic
});

// Export calendar
$('#exportCalendar').on('click', function() {
    alert('Calendar export functionality would be implemented here');
});

// Initialize calendar
$(document).ready(function() {
    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    
    // Initialize tooltips
    $('[data-bs-toggle="tooltip"]').tooltip();
});
</script>

<?php $this->endSection(); ?>
